/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";
import { useSpring, animated } from "react-spring";
import Lottie from "lottie-react";
import petBookingAnimation from "./animations/petBooking.json";

const BookingSection = () => {
  const buttonSpring = useSpring({
    from: { transform: "scale(1)" },
    to: async (next) => {
      while (true) {
        await next({ transform: "scale(1.05)" });
        await next({ transform: "scale(1)" });
      }
    },
    config: { duration: 1000 },
  });

  return (
    <section className="py-16 bg-purple-100">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.h2
          className="text-3xl font-bold text-center text-purple-800 mb-8"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          Ready to Make Your Pet Care Website Stand Out?
        </motion.h2>
        <div className="flex flex-col md:flex-row items-center justify-center">
          <div className="w-full md:w-1/2 mb-8 md:mb-0">
            <Lottie animationData={petBookingAnimation} loop={true} />
          </div>
          <div className="w-full md:w-1/2 text-center">
            <animated.button
              style={buttonSpring}
              className="bg-pink-500 hover:bg-pink-600 text-white font-bold py-3 px-6 rounded-full text-lg mb-4 transition duration-300"
            >
              Schedule a Free Consultation
            </animated.button>
            <p className="text-purple-700 mb-4">
              Let's create a paw-some website for your pet care business!
            </p>
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
            >
              <a
                href="tel:+1234567890"
                className="text-purple-600 hover:text-purple-800"
              >
                Call us: (123) 456-7890
              </a>
            </motion.div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default BookingSection;
