/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";
import Lottie from "lottie-react";
import pawPrintAnimation from "./animations/pawPrint.json";

const FooterSection = () => {
  const socialIcons = [
    { name: "Facebook", icon: "/icons/facebook.svg" },
    { name: "Twitter", icon: "/icons/twitter.svg" },
    { name: "Instagram", icon: "/icons/instagram.svg" },
    { name: "LinkedIn", icon: "/icons/linkedin.svg" },
  ];

  return (
    <footer className="bg-purple-800 text-white py-12">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div>
            <h3 className="text-xl font-bold mb-4">Quick Links</h3>
            <ul className="space-y-2">
              <li>
                <a
                  href="#portfolio"
                  className="hover:text-pink-300 transition duration-300"
                >
                  Portfolio
                </a>
              </li>
              <li>
                <a
                  href="#services"
                  className="hover:text-pink-300 transition duration-300"
                >
                  Services
                </a>
              </li>
              <li>
                <a
                  href="#testimonials"
                  className="hover:text-pink-300 transition duration-300"
                >
                  Testimonials
                </a>
              </li>
              <li>
                <a
                  href="#contact"
                  className="hover:text-pink-300 transition duration-300"
                >
                  Contact
                </a>
              </li>
            </ul>
          </div>
          <div>
            <h3 className="text-xl font-bold mb-4">Contact Info</h3>
            <p className="mb-2">Phone: (123) 456-7890</p>
            <p className="mb-2">Email: info@petanime.com</p>
            <p>123 Paw Street, Animeville, AN 12345</p>
          </div>
          <div>
            <h3 className="text-xl font-bold mb-4">Follow Us</h3>
            <div className="flex space-x-4">
              {socialIcons.map((social) => (
                <motion.a
                  key={social.name}
                  href={`#${social.name.toLowerCase()}`}
                  whileHover={{ scale: 1.1 }}
                  whileTap={{ scale: 0.9 }}
                >
                  <img
                    src={social.icon}
                    alt={social.name}
                    className="w-8 h-8"
                  />
                </motion.a>
              ))}
            </div>
          </div>
        </div>
        <div className="mt-8 pt-8 border-t border-purple-700 text-center">
          <p>&copy; 2023 PetAnime. All rights reserved.</p>
          <motion.button
            className="mt-4 bg-pink-500 hover:bg-pink-600 text-white font-bold py-2 px-4 rounded-full"
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}
          >
            Back to Top
          </motion.button>
        </div>
      </div>
      <div className="absolute bottom-0 right-0 w-24 h-24 opacity-50">
        <Lottie animationData={pawPrintAnimation} loop={true} />
      </div>
    </footer>
  );
};

export default FooterSection;
