/**
 * This code was generated by Builder.io.
 */
import React from "react";
import HeroSection from "./HeroSection";
import AboutUsSection from "./AboutUsSection";
import ServicesSection from "./ServicesSection";
import TestimonialsSection from "./TestimonialsSection";
import GallerySection from "./GallerySection";
import BookingSection from "./BookingSection";
import FooterSection from "./FooterSection";

const MainPage = () => {
  return (
    <div className="bg-purple-50 min-h-screen">
      <HeroSection />
      <AboutUsSection />
      <ServicesSection />
      <TestimonialsSection />
      <GallerySection />
      <BookingSection />
      <FooterSection />
    </div>
  );
};

export default MainPage;
