/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";

const testimonials = [
  {
    quote:
      "PetAnime transformed our website into an anime wonderland! Our clients love it!",
    author: "Yuki's Pet Paradise",
    avatar: "/images/anime-pet-avatar-1.jpg",
  },
  {
    quote:
      "The playful design increased our bookings by 50%! Thank you, PetAnime!",
    author: "Neko Nanny Services",
    avatar: "/images/anime-pet-avatar-2.jpg",
  },
  {
    quote:
      "Our website now truly reflects the joy and energy of our pet care services!",
    author: "Kawaii Kritters",
    avatar: "/images/anime-pet-avatar-3.jpg",
  },
];

const TestimonialCard = ({ testimonial, index }) => {
  return (
    <motion.div
      className="bg-white p-6 rounded-lg shadow-lg"
      initial={{ opacity: 0, y: 50 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: index * 0.1 }}
    >
      <div className="flex items-center mb-4">
        <img
          src={testimonial.avatar}
          alt={`${testimonial.author}'s pet avatar`}
          className="w-12 h-12 rounded-full mr-4"
        />
        <div>
          <p className="font-semibold text-purple-700">{testimonial.author}</p>
          <div className="text-yellow-400">★★★★★</div>
        </div>
      </div>
      <p className="text-gray-600 italic">"{testimonial.quote}"</p>
    </motion.div>
  );
};

const TestimonialsSection = () => {
  return (
    <section className="py-16 bg-purple-100">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.h2
          className="text-3xl font-bold text-center text-purple-800 mb-12"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          Happy Pets, Happy Clients!
        </motion.h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {testimonials.map((testimonial, index) => (
            <TestimonialCard
              key={index}
              testimonial={testimonial}
              index={index}
            />
          ))}
        </div>
      </div>
    </section>
  );
};

export default TestimonialsSection;
