/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { render, screen } from "@testing-library/react";
import { describe, it, expect } from "vitest";
import HeroSection from "../components/HeroSection";

describe("HeroSection", () => {
  it("renders the main heading", () => {
    render(<HeroSection />);
    const heading = screen.getByText(/Welcome to PetAnime/i);
    expect(heading).toBeInTheDocument();
  });

  it("renders the subheading", () => {
    render(<HeroSection />);
    const subheading = screen.getByText(/We design tail-wagging websites/i);
    expect(subheading).toBeInTheDocument();
  });

  it("renders the CTA buttons", () => {
    render(<HeroSection />);
    const consultationButton = screen.getByText(/Get a Free Consultation/i);
    const revampButton = screen.getByText(/Let's Revamp Your Site/i);
    expect(consultationButton).toBeInTheDocument();
    expect(revampButton).toBeInTheDocument();
  });
});
