/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { render, screen } from "@testing-library/react";
import { describe, it, expect } from "vitest";
import ServicesSection from "../components/ServicesSection";

describe("ServicesSection", () => {
  it("renders the section heading", () => {
    render(<ServicesSection />);
    const heading = screen.getByText(/Our Anime-Inspired Pet Care Services/i);
    expect(heading).toBeInTheDocument();
  });

  it("renders all service cards", () => {
    render(<ServicesSection />);
    const petSitting = screen.getByText(/Pet Sitting/i);
    const dogWalking = screen.getByText(/Dog Walking/i);
    const grooming = screen.getByText(/Grooming/i);
    const training = screen.getByText(/Training/i);
    expect(petSitting).toBeInTheDocument();
    expect(dogWalking).toBeInTheDocument();
    expect(grooming).toBeInTheDocument();
    expect(training).toBeInTheDocument();
  });
});
